version: 0.2

phases:
  pre_build:
    commands:
      - echo "===== ENV CHECK ====="
      - env | grep NVD || echo "NVD variable NOT FOUND"

  build:
    commands:
      - mvn clean install dependency-check:check

artifacts:
  files:
    - target/dependency-check-report.html
