version: 0.2

phases:
  pre_build:
    commands:
      - echo "Testing environment variable"
      - printenv | grep NVD

  build:
    commands:
      - mvn clean install dependency-check:check

artifacts:
  files:
    - target/dependency-check-report.html
